### ISSUE TITLE
Misc Thoughts

### ISSUE THREAD

**Issue by djspiewak** [runarorama/ircz#1]
Tossing this in a single issue since I'm too lazy to open separate ones…
## Bounded `mergeN`

The server as it is currently written can be trivially DoSed by launching a large number of client connections rapidly without awaiting a handshake.  This will result in the server simply running out of memory very rapidly.  The solution is actually pretty straightforward: specify a bound (preferably num cpus) on the server `mergeN` [here](https://github.com/runarorama/ircz/blob/master/src/main/scala/Server.scala#L61).  This causes `mergeN` to stop pulling connections, which fills up the scalaz-netty signal queue, which in turn disables `AUTO_READ` in the kernel's async IO layer and applies native, threadless TCP pushback on incoming connections.

Doesn't matter for a trivial demo, just best-practice sort of stuff.  Any `mergeN` without a bound is a sign of likely scalability problems (at the very least, it represents an elimination point for backpressure).
## Server Halt Conditions

Right now, I don't believe the server is going to halt uniformly.  This isn't a problem right now because you're (presumably) killing the server from the outside (ctrl-c), but you'll see it the instant you write any unit tests.  There are a couple areas that this affects, but the most notable one is `mainProcess`.  You should use `(_ wye _)(wye.mergeHaltBoth)` instead of `_ merge _`, to ensure that signals are propagated to both sides.  I could see skimping on this point for the sake of a more straightforward talk, but again, sort of a best practice thing.  It bites in real use cases.
## Daemons?

Why are you running on a fresh (unbounded!) daemon thread pool?  scalaz-netty is already thread shifting for you and it ensures that everything is properly insulated from the underlying Netty pool.  It is entirely safe to just use the default `Strategy`, and I'm not sure there's really much benefit in moving to a separate pool since you aren't performing any IO (all the IO is shifted and async).
## Client Halt Conditions

Speaking of `mergeHaltBoth`, you _absolutely_ need it [in the client](https://github.com/runarorama/ircz/blob/master/src/main/scala/Client.scala#L23).  Certain network errors/conditions will show up on the output side and not the input, while others will be the reverse.  It all depends on the topology between client and server.  Furthermore, if the server terminates the connection gracefully (and we're on a topology which propagates that signal), the `in` process will gracefully terminate without actually killing `out`!  This would result in a situation where we would need to sit there, awaiting input from the user only to throw it away when we received an error attempting to write to our long-dead connection.

**Comment by runarorama** [comment]
Awesome. Thanks for that!
